import type { Metadata } from "next";
import { Footer, Header } from "@/layouts";
import "../styles/normalize.css";
import "../styles/globals.css";
import { ContentStyled, FooterWrapper, LayoutGrid } from "./Layout.styled";
import StyledComponentsRegistry from "./registry";
import { inter, poppins } from "../../public/fonts";

export const metadata: Metadata = {
  title: "Frontend test",
  description: "Generated by GSerdg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <LayoutGrid>
            <Header />
          </LayoutGrid>
          <ContentStyled className={poppins.className}>{children}</ContentStyled>
          <FooterWrapper>
            <LayoutGrid>
              <Footer />
            </LayoutGrid>
          </FooterWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
