import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Header } from "@/layouts";
import "../styles/normalize.css";
import "../styles/globals.css";
import { LayoutGrid } from "./Layout.styled";
import StyledComponentsRegistry from "./registry";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <LayoutGrid>
            <Header />
          </LayoutGrid>
          {children}
          <LayoutGrid>
            <Footer />
          </LayoutGrid>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
